### ISSUE TITLE
Using the EPBot from python

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/Using-the-EPBot#1]
An example can be found at
https://github.com/lorserker/ben/blob/main/src/bba/BBA.py

**Comment by EdwardPiwowar** [comment]
Great. 
I don't know how you find time for all this. 
I mentioned the repository because it describes a possible layout of invisible cards and can also be used during the play.

**Comment by ThorvaldAagaard** [comment]
I think you should update the readme and create the link to BEN there - When you get time :-)
